# -*- coding: utf-8 -*-
"""Toy_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8KzSXleoGMp70Tj95rKL3oYPTb3fSqr
"""

import pandas as pd
import numpy as num

#File loading
df =pd.read_csv('/content/placement.csv')
df1 = df.iloc[:,1:]
# df1.head(10)

#Data visualization
import matplotlib.pyplot as plt
# plt.scatter(df1['cgpa'],df1['iq'],c=df1['placement'])
# plt.xlabel('CGPA')
# plt.ylabel('IQ')
# plt.show()

#Data modification
X= df1.iloc[:,0:2]
Y= df1.iloc[:,-1]
# print(X)
# print(Y)

#Traning Model
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1)
# print('Independent train variable Set size:',X_train.shape)
# print('Independent Test variable size; ',X_test.shape)
# print('Dependent train variable size:',Y_train.shape)
# print('Dependent test variable size: ',Y_test.shape)

# print(X_train)
# print(X_test)
# print(Y_train)
# print(Y_test)

#Scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

#Training Data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,Y_train)

#Evaluation
Y_Predict=model.predict(X_test)
print(Y_test)

#Accuracy Test
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_Predict)

#Plotting the decision
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X_train, Y_train.values, clf=model, legend=2)
plt.xlabel('CGPA')
plt.ylabel('IQ')
plt.show()